### ISSUE TITLE
Minor issues with the edit and the delete commands.

### ISSUE THREAD

**Issue by Salvi0** [ThePhoDit/ModMail#10]
While testing all the bot features i noticed something strange on both the edit and delete commands. Exactly in the logs.

When the delete command is used on an already deleted message it will say that the message is not found, but on the logs this happens. 
![delete command problem here.](https://user-images.githubusercontent.com/66015217/135106097-5c1e22c5-4b69-4caf-b99a-c55e612821e0.png)
In conjuction with this problem also using the edit command will make the bot answer that no message is actually found, but on the logs well.
![edit command problem here.](https://user-images.githubusercontent.com/66015217/135106502-4a1cbdd3-1acd-4fea-a16e-09149dafba33.png)

**Comment by ThePhoDit** [comment]
This looks like something easy to address, I will be fixing it soon this week.
I will let you know here whenever it's done.

**Comment by ThePhoDit** [comment]
Should now be fixed with version 3.0.4

**Comment by Salvi0** [comment]
Alright :3
